import { ComponentVariants } from '../types';

/**
 * Generate CSS for component variants
 */
export function generateVariantsCSS(variants: ComponentVariants): string {
  return `/* Component Variants - Generated by Hyena Studio */
/* ${new Date().toISOString()} */

/* ============================================
   BUTTON VARIANTS
   ============================================ */

.btn-primary {
  background-color: ${variants.button.primary.background};
  color: ${variants.button.primary.text};
  border: 1px solid ${variants.button.primary.border};
}
.btn-primary:hover {
  background-color: ${variants.button.primary.hoverBackground};
  color: ${variants.button.primary.hoverText};
  border-color: ${variants.button.primary.hoverBorder};
}
.btn-primary:active {
  background-color: ${variants.button.primary.activeBackground};
}
.btn-primary:disabled {
  background-color: ${variants.button.primary.disabledBackground};
  color: ${variants.button.primary.disabledText};
  cursor: not-allowed;
}

.btn-secondary {
  background-color: ${variants.button.secondary.background};
  color: ${variants.button.secondary.text};
  border: 1px solid ${variants.button.secondary.border};
}
.btn-secondary:hover {
  background-color: ${variants.button.secondary.hoverBackground};
  color: ${variants.button.secondary.hoverText};
  border-color: ${variants.button.secondary.hoverBorder};
}
.btn-secondary:active {
  background-color: ${variants.button.secondary.activeBackground};
}
.btn-secondary:disabled {
  background-color: ${variants.button.secondary.disabledBackground};
  color: ${variants.button.secondary.disabledText};
  cursor: not-allowed;
}

.btn-outline {
  background-color: ${variants.button.outline.background};
  color: ${variants.button.outline.text};
  border: 1px solid ${variants.button.outline.border};
}
.btn-outline:hover {
  background-color: ${variants.button.outline.hoverBackground};
  color: ${variants.button.outline.hoverText};
  border-color: ${variants.button.outline.hoverBorder};
}
.btn-outline:active {
  background-color: ${variants.button.outline.activeBackground};
}
.btn-outline:disabled {
  background-color: ${variants.button.outline.disabledBackground};
  color: ${variants.button.outline.disabledText};
  cursor: not-allowed;
}

.btn-ghost {
  background-color: ${variants.button.ghost.background};
  color: ${variants.button.ghost.text};
  border: 1px solid ${variants.button.ghost.border};
}
.btn-ghost:hover {
  background-color: ${variants.button.ghost.hoverBackground};
  color: ${variants.button.ghost.hoverText};
  border-color: ${variants.button.ghost.hoverBorder};
}
.btn-ghost:active {
  background-color: ${variants.button.ghost.activeBackground};
}
.btn-ghost:disabled {
  background-color: ${variants.button.ghost.disabledBackground};
  color: ${variants.button.ghost.disabledText};
  cursor: not-allowed;
}

.btn-destructive {
  background-color: ${variants.button.destructive.background};
  color: ${variants.button.destructive.text};
  border: 1px solid ${variants.button.destructive.border};
}
.btn-destructive:hover {
  background-color: ${variants.button.destructive.hoverBackground};
  color: ${variants.button.destructive.hoverText};
  border-color: ${variants.button.destructive.hoverBorder};
}
.btn-destructive:active {
  background-color: ${variants.button.destructive.activeBackground};
}
.btn-destructive:disabled {
  background-color: ${variants.button.destructive.disabledBackground};
  color: ${variants.button.destructive.disabledText};
  cursor: not-allowed;
}

.btn-link {
  background-color: ${variants.button.link.background};
  color: ${variants.button.link.text};
  border: 1px solid ${variants.button.link.border};
  text-decoration: underline;
}
.btn-link:hover {
  background-color: ${variants.button.link.hoverBackground};
  color: ${variants.button.link.hoverText};
  border-color: ${variants.button.link.hoverBorder};
}
.btn-link:disabled {
  background-color: ${variants.button.link.disabledBackground};
  color: ${variants.button.link.disabledText};
  cursor: not-allowed;
}

/* ============================================
   INPUT VARIANTS
   ============================================ */

.input {
  background-color: ${variants.input.background};
  color: ${variants.input.text};
  border: 1px solid ${variants.input.border};
}
.input::placeholder {
  color: ${variants.input.placeholder};
}
.input:focus {
  border-color: ${variants.input.focusBorder};
  box-shadow: 0 0 0 3px ${variants.input.focusRing};
  outline: none;
}
.input-error {
  background-color: ${variants.input.errorBackground};
  border-color: ${variants.input.errorBorder};
  color: ${variants.input.errorText};
}
.input:disabled {
  background-color: ${variants.input.disabledBackground};
  color: ${variants.input.disabledText};
  cursor: not-allowed;
}

/* ============================================
   CARD VARIANTS
   ============================================ */

.card {
  background-color: ${variants.card.default.background};
  border: 1px solid ${variants.card.default.border};
  box-shadow: ${variants.card.default.shadow};
}
.card-header {
  background-color: ${variants.card.default.headerBackground};
}
.card-footer {
  background-color: ${variants.card.default.footerBackground};
}

.card-elevated {
  background-color: ${variants.card.elevated.background};
  border: 1px solid ${variants.card.elevated.border};
  box-shadow: ${variants.card.elevated.shadow};
}
.card-elevated .card-footer {
  background-color: ${variants.card.elevated.footerBackground};
}

.card-outlined {
  background-color: ${variants.card.outlined.background};
  border: 1px solid ${variants.card.outlined.border};
  box-shadow: ${variants.card.outlined.shadow};
}
.card-outlined .card-footer {
  background-color: ${variants.card.outlined.footerBackground};
}

.card-filled {
  background-color: ${variants.card.filled.background};
  border: 1px solid ${variants.card.filled.border};
  box-shadow: ${variants.card.filled.shadow};
}
.card-filled .card-footer {
  background-color: ${variants.card.filled.footerBackground};
}

/* ============================================
   BADGE VARIANTS
   ============================================ */

.badge {
  background-color: ${variants.badge.default.background};
  color: ${variants.badge.default.text};
  border: 1px solid ${variants.badge.default.border};
}

.badge-primary {
  background-color: ${variants.badge.primary.background};
  color: ${variants.badge.primary.text};
  border: 1px solid ${variants.badge.primary.border};
}

.badge-secondary {
  background-color: ${variants.badge.secondary.background};
  color: ${variants.badge.secondary.text};
  border: 1px solid ${variants.badge.secondary.border};
}

.badge-success {
  background-color: ${variants.badge.success.background};
  color: ${variants.badge.success.text};
  border: 1px solid ${variants.badge.success.border};
}

.badge-warning {
  background-color: ${variants.badge.warning.background};
  color: ${variants.badge.warning.text};
  border: 1px solid ${variants.badge.warning.border};
}

.badge-error {
  background-color: ${variants.badge.error.background};
  color: ${variants.badge.error.text};
  border: 1px solid ${variants.badge.error.border};
}

.badge-info {
  background-color: ${variants.badge.info.background};
  color: ${variants.badge.info.text};
  border: 1px solid ${variants.badge.info.border};
}

.badge-outline {
  background-color: ${variants.badge.outline.background};
  color: ${variants.badge.outline.text};
  border: 1px solid ${variants.badge.outline.border};
}

/* ============================================
   ALERT VARIANTS
   ============================================ */

.alert {
  background-color: ${variants.alert.default.background};
  color: ${variants.alert.default.text};
  border: 1px solid ${variants.alert.default.border};
}
.alert .alert-icon {
  color: ${variants.alert.default.icon};
}

.alert-success {
  background-color: ${variants.alert.success.background};
  color: ${variants.alert.success.text};
  border: 1px solid ${variants.alert.success.border};
}
.alert-success .alert-icon {
  color: ${variants.alert.success.icon};
}

.alert-warning {
  background-color: ${variants.alert.warning.background};
  color: ${variants.alert.warning.text};
  border: 1px solid ${variants.alert.warning.border};
}
.alert-warning .alert-icon {
  color: ${variants.alert.warning.icon};
}

.alert-error {
  background-color: ${variants.alert.error.background};
  color: ${variants.alert.error.text};
  border: 1px solid ${variants.alert.error.border};
}
.alert-error .alert-icon {
  color: ${variants.alert.error.icon};
}

.alert-info {
  background-color: ${variants.alert.info.background};
  color: ${variants.alert.info.text};
  border: 1px solid ${variants.alert.info.border};
}
.alert-info .alert-icon {
  color: ${variants.alert.info.icon};
}
`;
}

/**
 * Generate JSON export for variants
 */
export function generateVariantsJSON(variants: ComponentVariants): string {
  return JSON.stringify(variants, null, 2);
}

/**
 * Generate Tailwind CSS plugin for variants
 */
export function generateVariantsTailwind(variants: ComponentVariants): string {
  return `// Component Variants Plugin - Generated by Hyena Studio
// ${new Date().toISOString()}

const plugin = require('tailwindcss/plugin');

module.exports = plugin(function({ addComponents }) {
  addComponents({
    // Button variants
    '.btn-primary': {
      backgroundColor: '${variants.button.primary.background}',
      color: '${variants.button.primary.text}',
      borderColor: '${variants.button.primary.border}',
      borderWidth: '1px',
      borderStyle: 'solid',
      '&:hover': {
        backgroundColor: '${variants.button.primary.hoverBackground}',
        color: '${variants.button.primary.hoverText}',
        borderColor: '${variants.button.primary.hoverBorder}',
      },
      '&:active': {
        backgroundColor: '${variants.button.primary.activeBackground}',
      },
      '&:disabled': {
        backgroundColor: '${variants.button.primary.disabledBackground}',
        color: '${variants.button.primary.disabledText}',
        cursor: 'not-allowed',
      },
    },
    '.btn-secondary': {
      backgroundColor: '${variants.button.secondary.background}',
      color: '${variants.button.secondary.text}',
      borderColor: '${variants.button.secondary.border}',
      borderWidth: '1px',
      borderStyle: 'solid',
      '&:hover': {
        backgroundColor: '${variants.button.secondary.hoverBackground}',
        color: '${variants.button.secondary.hoverText}',
        borderColor: '${variants.button.secondary.hoverBorder}',
      },
      '&:active': {
        backgroundColor: '${variants.button.secondary.activeBackground}',
      },
      '&:disabled': {
        backgroundColor: '${variants.button.secondary.disabledBackground}',
        color: '${variants.button.secondary.disabledText}',
        cursor: 'not-allowed',
      },
    },
    '.btn-outline': {
      backgroundColor: 'transparent',
      color: '${variants.button.outline.text}',
      borderColor: '${variants.button.outline.border}',
      borderWidth: '1px',
      borderStyle: 'solid',
      '&:hover': {
        backgroundColor: '${variants.button.outline.hoverBackground}',
        color: '${variants.button.outline.hoverText}',
        borderColor: '${variants.button.outline.hoverBorder}',
      },
      '&:active': {
        backgroundColor: '${variants.button.outline.activeBackground}',
      },
      '&:disabled': {
        backgroundColor: '${variants.button.outline.disabledBackground}',
        color: '${variants.button.outline.disabledText}',
        cursor: 'not-allowed',
      },
    },
    '.btn-ghost': {
      backgroundColor: 'transparent',
      color: '${variants.button.ghost.text}',
      borderColor: 'transparent',
      borderWidth: '1px',
      borderStyle: 'solid',
      '&:hover': {
        backgroundColor: '${variants.button.ghost.hoverBackground}',
        color: '${variants.button.ghost.hoverText}',
      },
      '&:active': {
        backgroundColor: '${variants.button.ghost.activeBackground}',
      },
      '&:disabled': {
        backgroundColor: '${variants.button.ghost.disabledBackground}',
        color: '${variants.button.ghost.disabledText}',
        cursor: 'not-allowed',
      },
    },
    '.btn-destructive': {
      backgroundColor: '${variants.button.destructive.background}',
      color: '${variants.button.destructive.text}',
      borderColor: '${variants.button.destructive.border}',
      borderWidth: '1px',
      borderStyle: 'solid',
      '&:hover': {
        backgroundColor: '${variants.button.destructive.hoverBackground}',
        color: '${variants.button.destructive.hoverText}',
        borderColor: '${variants.button.destructive.hoverBorder}',
      },
      '&:active': {
        backgroundColor: '${variants.button.destructive.activeBackground}',
      },
      '&:disabled': {
        backgroundColor: '${variants.button.destructive.disabledBackground}',
        color: '${variants.button.destructive.disabledText}',
        cursor: 'not-allowed',
      },
    },
    '.btn-link': {
      backgroundColor: 'transparent',
      color: '${variants.button.link.text}',
      borderColor: 'transparent',
      textDecoration: 'underline',
      '&:hover': {
        color: '${variants.button.link.hoverText}',
      },
      '&:disabled': {
        color: '${variants.button.link.disabledText}',
        cursor: 'not-allowed',
      },
    },

    // Input variants
    '.input': {
      backgroundColor: '${variants.input.background}',
      color: '${variants.input.text}',
      borderColor: '${variants.input.border}',
      borderWidth: '1px',
      borderStyle: 'solid',
      '&::placeholder': {
        color: '${variants.input.placeholder}',
      },
      '&:focus': {
        borderColor: '${variants.input.focusBorder}',
        boxShadow: '0 0 0 3px ${variants.input.focusRing}',
        outline: 'none',
      },
      '&:disabled': {
        backgroundColor: '${variants.input.disabledBackground}',
        color: '${variants.input.disabledText}',
        cursor: 'not-allowed',
      },
    },
    '.input-error': {
      backgroundColor: '${variants.input.errorBackground}',
      borderColor: '${variants.input.errorBorder}',
      color: '${variants.input.errorText}',
    },

    // Card variants
    '.card': {
      backgroundColor: '${variants.card.default.background}',
      borderColor: '${variants.card.default.border}',
      borderWidth: '1px',
      borderStyle: 'solid',
      boxShadow: '${variants.card.default.shadow}',
    },
    '.card-elevated': {
      backgroundColor: '${variants.card.elevated.background}',
      boxShadow: '${variants.card.elevated.shadow}',
    },
    '.card-outlined': {
      backgroundColor: '${variants.card.outlined.background}',
      borderColor: '${variants.card.outlined.border}',
      borderWidth: '1px',
      borderStyle: 'solid',
    },
    '.card-filled': {
      backgroundColor: '${variants.card.filled.background}',
    },

    // Badge variants
    '.badge': {
      backgroundColor: '${variants.badge.default.background}',
      color: '${variants.badge.default.text}',
    },
    '.badge-primary': {
      backgroundColor: '${variants.badge.primary.background}',
      color: '${variants.badge.primary.text}',
    },
    '.badge-secondary': {
      backgroundColor: '${variants.badge.secondary.background}',
      color: '${variants.badge.secondary.text}',
    },
    '.badge-success': {
      backgroundColor: '${variants.badge.success.background}',
      color: '${variants.badge.success.text}',
    },
    '.badge-warning': {
      backgroundColor: '${variants.badge.warning.background}',
      color: '${variants.badge.warning.text}',
    },
    '.badge-error': {
      backgroundColor: '${variants.badge.error.background}',
      color: '${variants.badge.error.text}',
    },
    '.badge-info': {
      backgroundColor: '${variants.badge.info.background}',
      color: '${variants.badge.info.text}',
    },
    '.badge-outline': {
      backgroundColor: '${variants.badge.outline.background}',
      color: '${variants.badge.outline.text}',
      borderColor: '${variants.badge.outline.border}',
      borderWidth: '1px',
      borderStyle: 'solid',
    },

    // Alert variants
    '.alert': {
      backgroundColor: '${variants.alert.default.background}',
      color: '${variants.alert.default.text}',
      borderColor: '${variants.alert.default.border}',
      borderWidth: '1px',
      borderStyle: 'solid',
    },
    '.alert-success': {
      backgroundColor: '${variants.alert.success.background}',
      color: '${variants.alert.success.text}',
      borderColor: '${variants.alert.success.border}',
    },
    '.alert-warning': {
      backgroundColor: '${variants.alert.warning.background}',
      color: '${variants.alert.warning.text}',
      borderColor: '${variants.alert.warning.border}',
    },
    '.alert-error': {
      backgroundColor: '${variants.alert.error.background}',
      color: '${variants.alert.error.text}',
      borderColor: '${variants.alert.error.border}',
    },
    '.alert-info': {
      backgroundColor: '${variants.alert.info.background}',
      color: '${variants.alert.info.text}',
      borderColor: '${variants.alert.info.border}',
    },
  });
});
`;
}
